### ISSUE TITLE
session存储问题

### ISSUE THREAD

**Issue by bqey** [avidbyte/netty-websocket#1]
想将session持久化到redis，但是序列化一直不支持

**Comment by avidbyte** [comment]
感谢反馈，我先看看如何解决，会在下个版本支持 session 的序列化，之后你可以在新版本里再看看。

**Comment by avidbyte** [comment]
你好，我认真考虑了这个问题，Session 序列化这个操作本质上还是集群架构上 Session 的集中存储。目前项目中 Session 中包含 Channel，在 Netty 中，Channel 是一个重要的概念，代表了一个开放的连接，可以进行数据的读写。将 Netty 中的 Channel 对象序列化到 Redis 中，可能会面临一些问题。Channel 对象通常包含与底层网络连接相关的状态，这些状态在序列化和反序列化时可能会导致问题。另外，Channel 对象的序列化也可能不是一种明智的做法，因为它通常表示一个瞬时的网络连接，而不是一种持久化的数据。

我这边设想了一个场景。如果你想在 WebSocket 集群中给一批用户发送数据，有一些更常见的做法，
而不是直接序列化和存储 Session 对象到 Redis 中。以下是一些可能的方法：

1.使用集中式消息队列： 发布订阅模型是一种有效的方法，可以将需要发送的消息发布到消息队列中，然后让各个节点进行订阅并将消息发送到各自的 WebSocket 客户端。

2.共享信息存储： 将需要发送的数据存储在一个共享的数据库中，每个节点可以从数据库中获取数据并发送给对应的 WebSocket 客户端。这通常需要考虑数据库的读写性能和一致性。

3.使用分布式缓存： 类似于共享信息存储，可以使用分布式缓存来存储需要发送的数据。每个节点可以从缓存中获取数据并发送给相应的客户端。这也需要考虑缓存的一致性和性能。

**Comment by avidbyte** [comment]
如果没有其他问题 我将会关闭这个 Issue @bqey
